#dependencias

FROM node:22-alpine as deps 
WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm install





#builder - construye la aplicacion 
FROM node:22-alpine as builder

WORKDIR /usr/src/app

#copiar de deps, los modulos de node

COPY --from=deps /usr/src/app/node_modules ./node_modules

#copiar todo el codigo fuente de la aplicacion
COPY . .

RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force


# produccion

FROM node:22-alpine as prod

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist

USER node

EXPOSE 3001

CMD ["node", "dist/main.js"]